In [33]:
#importation des bibliothéques
import numpy as np
import matplotlib.pyplot as plt
import copy
import pandas as pd
from sklearn.metrics import mean_squared_error

In [34]:
train_data_all=pd.read_excel(r"E:\Hraf\S8\Projet à Enjeux\Projet Enjeux\dataset_contact_all.xlsx")#Rq:génerer le dataset avec le programme dataset.py pour charger le dataset
train_data_all=train_data_all.to_numpy() #transfomer la data from dataframe to numpy

In [35]:
train_data_home=pd.read_excel(r"E:\Hraf\S8\Projet à Enjeux\Projet Enjeux\dataset_contact_home.xlsx")#Rq:génerer le dataset avec le programme dataset.py pour charger le dataset
train_data_home=train_data_home.to_numpy() #transfomer la data from dataframe to numpy

In [36]:
train_data_others=pd.read_excel(r"E:\Hraf\S8\Projet à Enjeux\Projet Enjeux\dataset_contact_others.xlsx")#Rq:génerer le dataset avec le programme dataset.py pour charger le dataset
train_data_others=train_data_others.to_numpy() #transfomer la data from dataframe to numpy

In [37]:
train_data_school=pd.read_excel(r"E:\Hraf\S8\Projet à Enjeux\Projet Enjeux\dataset_contact_school.xlsx")#Rq:génerer le dataset avec le programme dataset.py pour charger le dataset
train_data_school=train_data_school.to_numpy() #transfomer la data from dataframe to numpy

In [38]:
train_data_work=pd.read_excel(r"E:\Hraf\S8\Projet à Enjeux\Projet Enjeux\dataset_contact_work.xlsx")#Rq:génerer le dataset avec le programme dataset.py pour charger le dataset
train_data_work=train_data_work.to_numpy() #transfomer la data from dataframe to numpy

In [39]:

test_set_x_orig_all=np.zeros((30,512))

X_test_all=pd.read_excel(r"E:\Hraf\S8\Projet à Enjeux\Projet Enjeux\input_seri_all.xlsx")#Rq:génerer le dataset avec le programme dataset.py pour charger le dataset
X_test_all=X_test_all.to_numpy()

for i in range (30):
    for j in range(1,513):
                test_set_x_orig_all[i][j-1]=X_test_all[i][j]
    
test_set_x_orig_all=np.transpose(test_set_x_orig_all) 
m=np.mean(test_set_x_orig_all) #moyenne
v=np.std(test_set_x_orig_all) #écart type
test_set_x_orig_all=(test_set_x_orig_all-m)/v # centralize, strandarize the data
print(test_set_x_orig_all) # test_set_x_orig est un array de taille (512,1) , 512=64*r , pour chaque catégorie d'age , il'ya les valeurs de S,E,I,R


[[ 3.50738945  3.50749904  3.50745356 ...  3.50735007  3.50734013
   3.50737145]
 [ 2.96153078  3.23309847  3.07626903 ...  2.83341004  2.81759605
   2.88372902]
 [ 0.28279201  0.62147141  0.28672269 ... -0.054153   -0.09039011
  -0.02613343]
 ...
 [-0.45530458 -0.45530458 -0.45530458 ... -0.45530458 -0.45530458
  -0.45530458]
 [-0.45530458 -0.45530458 -0.45530458 ... -0.45530458 -0.45530458
  -0.45530458]
 [-0.45530458 -0.45530458 -0.45530458 ... -0.45530458 -0.45530458
  -0.45530458]]


In [40]:
test_set_x_orig_home=np.zeros((30,512))

X_test_home=pd.read_excel(r"E:\Hraf\S8\Projet à Enjeux\Projet Enjeux\input_seri_home.xlsx")#Rq:génerer le dataset avec le programme dataset.py pour charger le dataset
X_test_home=X_test_home.to_numpy()

for i in range (30):
    for j in range(1,513):
                test_set_x_orig_home[i][j-1]=X_test_home[i][j]
    
test_set_x_orig_home=np.transpose(test_set_x_orig_home) 
m=np.mean(test_set_x_orig_home) #moyenne
v=np.std(test_set_x_orig_home) #écart type
test_set_x_orig_home=(test_set_x_orig_home-m)/v # centralize, strandarize the data
print(test_set_x_orig_home) # test_set_x_orig est un array de taille (512,1) , 512=64*r , pour chaque catégorie d'age , il'ya les valeurs de S,E,I,R

[[ 2.66900344  2.66900294  2.66900352 ...  2.66900316  2.66900319
   2.66900348]
 [ 2.66882262  2.66865565  2.66884469 ...  2.66873963  2.66875637
   2.66884353]
 [ 2.64807825  2.61393854  2.6518701  ...  2.63234841  2.63592062
   2.65202278]
 ...
 [-0.50026157 -0.50026128 -0.50026167 ... -0.50026156 -0.50026161
  -0.50026184]
 [-0.50026117 -0.50026116 -0.50026117 ... -0.50026117 -0.50026117
  -0.50026118]
 [-0.50026116 -0.50026116 -0.50026116 ... -0.50026116 -0.50026116
  -0.50026116]]


In [41]:
test_set_x_orig_others=np.zeros((30,512))

X_test_others=pd.read_excel(r"E:\Hraf\S8\Projet à Enjeux\Projet Enjeux\input_seri_others.xlsx")#Rq:génerer le dataset avec le programme dataset.py pour charger le dataset
X_test_others=X_test_others.to_numpy()

for i in range (30):
    for j in range(1,513):
                test_set_x_orig_others[i][j-1]=X_test_others[i][j]
    
test_set_x_orig_others=np.transpose(test_set_x_orig_others) 
m=np.mean(test_set_x_orig_others) #moyenne
v=np.std(test_set_x_orig_others) #écart type
test_set_x_orig_others=(test_set_x_orig_others-m)/v # centralize, strandarize the data
print(test_set_x_orig_others) # test_set_x_orig est un array de taille (512,1) , 512=64*r , pour chaque catégorie d'age , il'ya les valeurs de S,E,I,R

[[ 2.54523925  2.54523929  2.54523914 ...  2.5452387   2.54523861
   2.54523863]
 [ 2.54520982  2.54523373  2.54521544 ...  2.54513327  2.54514031
   2.54516317]
 [ 2.54061804  2.54497742  2.54326468 ...  2.53080833  2.53388292
   2.53827345]
 ...
 [-0.51888912 -0.51890606 -0.51888744 ... -0.51888467 -0.51888609
  -0.51888608]
 [-0.51888239 -0.51888227 -0.51888112 ... -0.51888103 -0.5188811
  -0.51888104]
 [-0.51888117 -0.5188809  -0.51888086 ... -0.51888086 -0.51888086
  -0.51888085]]


In [42]:
test_set_x_orig_school=np.zeros((30,512))

X_test_school=pd.read_excel(r"E:\Hraf\S8\Projet à Enjeux\Projet Enjeux\input_seri_school.xlsx")#Rq:génerer le dataset avec le programme dataset.py pour charger le dataset
X_test_school=X_test_school.to_numpy()

for i in range (30):
    for j in range(1,513):
                test_set_x_orig_school[i][j-1]=X_test_school[i][j]
    
test_set_x_orig_school=np.transpose(test_set_x_orig_school) 
m=np.mean(test_set_x_orig_school) #moyenne
v=np.std(test_set_x_orig_school) #écart type
test_set_x_orig_school=(test_set_x_orig_school-m)/v # centralize, strandarize the data
print(test_set_x_orig_school) # test_set_x_orig est un array de taille (512,1) , 512=64*r , pour chaque catégorie d'age , il'ya les valeurs de S,E,I,R

[[ 1.73205123  1.73205123  1.73205123 ...  1.73205123  1.73205123
   1.73205123]
 [ 1.73205123  1.73205123  1.73205123 ...  1.73205123  1.73205123
   1.73205123]
 [ 1.73205123  1.73205123  1.73205123 ...  1.73205123  1.73205123
   1.73205123]
 ...
 [-0.57735027 -0.57735027 -0.57735027 ... -0.57735027 -0.57735027
  -0.57735027]
 [-0.57735027 -0.57735027 -0.57735027 ... -0.57735027 -0.57735027
  -0.57735027]
 [-0.57735027 -0.57735027 -0.57735027 ... -0.57735027 -0.57735027
  -0.57735027]]


In [43]:
test_set_x_orig_work=np.zeros((30,512))

X_test_work=pd.read_excel(r"E:\Hraf\S8\Projet à Enjeux\Projet Enjeux\input_seri_work.xlsx")#Rq:génerer le dataset avec le programme dataset.py pour charger le dataset
X_test_work=X_test_work.to_numpy()

for i in range (30):
    for j in range(1,513):
                test_set_x_orig_work[i][j-1]=X_test_work[i][j]
    
test_set_x_orig_work=np.transpose(test_set_x_orig_work) 
m=np.mean(test_set_x_orig_work) #moyenne
v=np.std(test_set_x_orig_work) #écart type
test_set_x_orig_work=(test_set_x_orig_work-m)/v # centralize, strandarize the data
print(test_set_x_orig_work) # test_set_x_orig est un array de taille (512,1) , 512=64*r , pour chaque catégorie d'age , il'ya les valeurs de S,E,I,R

[[ 2.45411089  2.45411102  2.45411086 ...  2.45411084  2.45411076
   2.45411075]
 [ 2.45409479  2.45410754  2.45409065 ...  2.45408672  2.45407177
   2.45406983]
 [ 2.4531217   2.45401667  2.45271012 ...  2.45227604  2.45034757
   2.45002952]
 ...
 [-0.54881229 -0.54890205 -0.54880521 ... -0.54880156 -0.54878439
  -0.54877986]
 [-0.54878065 -0.54884135 -0.54877653 ... -0.548777   -0.54876392
  -0.54875822]
 [-0.54876847 -0.54881025 -0.54876473 ... -0.54876737 -0.54875546
  -0.54874869]]


In [44]:
r=8
# importation de la data d'entrenement , on va entrainer notre modele avec 32 instances
train_set_x_orig_all=np.zeros((120,64*r))
for i in range(120):
    for j in range(1,64*r+1):
        train_set_x_orig_all[i][j-1]=train_data_all[i][j]
train_set_x_orig_all=np.transpose(train_set_x_orig_all)          
m=np.mean(train_set_x_orig_all) #moyenne
v=np.std(train_set_x_orig_all) #écart type
train_set_x_orig_all=(train_set_x_orig_all-m)/v # centralize, strandarize the data
#train_set_x_orig=(train_set_x_orig)/np.max(train_set_x_orig)
print(np.shape(train_set_x_orig_all)) 

(512, 120)


In [45]:
r=8
# importation de la data d'entrenement , on va entrainer notre modele avec 32 instances
train_set_x_orig_home=np.zeros((120,64*r))
for i in range(120):
    for j in range(1,64*r+1):
        train_set_x_orig_home[i][j-1]=train_data_home[i][j]
train_set_x_orig_home=np.transpose(train_set_x_orig_home)          
m=np.mean(train_set_x_orig_home) #moyenne
v=np.std(train_set_x_orig_home) #écart type
train_set_x_orig_home=(train_set_x_orig_home-m)/v # centralize, strandarize the data
#train_set_x_orig=(train_set_x_orig)/np.max(train_set_x_orig)
print(np.shape(train_set_x_orig_home)) 

(512, 120)


In [46]:
r=8
# importation de la data d'entrenement , on va entrainer notre modele avec 32 instances
train_set_x_orig_others=np.zeros((120,64*r))
for i in range(120):
    for j in range(1,64*r+1):
        train_set_x_orig_others[i][j-1]=train_data_others[i][j]
train_set_x_orig_others=np.transpose(train_set_x_orig_others)          
m=np.mean(train_set_x_orig_others) #moyenne
v=np.std(train_set_x_orig_others) #écart type
train_set_x_orig_others=(train_set_x_orig_others-m)/v # centralize, strandarize the data
#train_set_x_orig=(train_set_x_orig)/np.max(train_set_x_orig)
print(np.shape(train_set_x_orig_others)) 

(512, 120)


In [47]:
r=8
# importation de la data d'entrenement , on va entrainer notre modele avec 32 instances
train_set_x_orig_school=np.zeros((120,64*r))
for i in range(120):
    for j in range(1,64*r+1):
        train_set_x_orig_school[i][j-1]=train_data_school[i][j]
train_set_x_orig_school=np.transpose(train_set_x_orig_school)          
m=np.mean(train_set_x_orig_school) #moyenne
v=np.std(train_set_x_orig_school) #écart type
train_set_x_orig_school=(train_set_x_orig_school-m)/v # centralize, strandarize the data
#train_set_x_orig=(train_set_x_orig)/np.max(train_set_x_orig)
print(np.shape(train_set_x_orig_school)) 

(512, 120)


In [48]:
r=8
# importation de la data d'entrenement , on va entrainer notre modele avec 32 instances
train_set_x_orig_work=np.zeros((120,64*r))
for i in range(120):
    for j in range(1,64*r+1):
        train_set_x_orig_work[i][j-1]=train_data_work[i][j]
train_set_x_orig_work=np.transpose(train_set_x_orig_work)          
m=np.mean(train_set_x_orig_work) #moyenne
v=np.std(train_set_x_orig_work) #écart type
train_set_x_orig_work=(train_set_x_orig_work-m)/v # centralize, strandarize the data
#train_set_x_orig=(train_set_x_orig)/np.max(train_set_x_orig)
print(np.shape(train_set_x_orig_work)) 

(512, 120)


In [49]:
r=8
#importation des output(valeurs de contact) de la data d'entrainement
train_set_y_m_all=np.zeros((120,256))
for i in range(120):
    for j in range(1,257):
        train_set_y_m_all[i][j-1]=train_data_all[i][j+(r*64)]

train_set_y_m_all=np.transpose(train_set_y_m_all)    
#m=np.mean(train_set_y) #moyenne
#v=np.std(train_set_y) #écart type
#train_set_y=(train_set_y-m)/v   # centralize, strandarize the data
train_set_y_all=train_set_y_m_all/np.max(train_set_y_m_all)
print(np.shape(train_set_y_all)) 

(256, 120)


In [50]:
r=8
#importation des output(valeurs de contact) de la data d'entrainement
train_set_y_m_home=np.zeros((120,256))
for i in range(120):
    for j in range(1,257):
        train_set_y_m_home[i][j-1]=train_data_home[i][j+(r*64)]

train_set_y_m_home=np.transpose(train_set_y_m_home)    
#m=np.mean(train_set_y) #moyenne
#v=np.std(train_set_y) #écart type
#train_set_y=(train_set_y-m)/v   # centralize, strandarize the data
train_set_y_home=train_set_y_m_home/np.max(train_set_y_m_home)
print(np.shape(train_set_y_home)) 

(256, 120)


In [51]:
r=8
#importation des output(valeurs de contact) de la data d'entrainement
train_set_y_m_others=np.zeros((120,256))
for i in range(120):
    for j in range(1,257):
        train_set_y_m_others[i][j-1]=train_data_others[i][j+(r*64)]

train_set_y_m_others=np.transpose(train_set_y_m_others)    
#m=np.mean(train_set_y) #moyenne
#v=np.std(train_set_y) #écart type
#train_set_y=(train_set_y-m)/v   # centralize, strandarize the data
train_set_y_others=train_set_y_m_others/np.max(train_set_y_m_others)
print(np.shape(train_set_y_others)) 

(256, 120)


In [52]:
r=8
#importation des output(valeurs de contact) de la data d'entrainement
train_set_y_m_school=np.zeros((120,256))
for i in range(120):
    for j in range(1,257):
        train_set_y_m_school[i][j-1]=train_data_school[i][j+(r*64)]

train_set_y_m_school=np.transpose(train_set_y_m_school)    
#m=np.mean(train_set_y) #moyenne
#v=np.std(train_set_y) #écart type
#train_set_y=(train_set_y-m)/v   # centralize, strandarize the data
train_set_y_school=train_set_y_m_school/np.max(train_set_y_m_school)
print(np.shape(train_set_y_school)) 

(256, 120)


In [53]:
r=8
#importation des output(valeurs de contact) de la data d'entrainement
train_set_y_m_work=np.zeros((120,256))
for i in range(120):
    for j in range(1,257):
        train_set_y_m_work[i][j-1]=train_data_work[i][j+(r*64)]

train_set_y_m_work=np.transpose(train_set_y_m_work)    
#m=np.mean(train_set_y) #moyenne
#v=np.std(train_set_y) #écart type
#train_set_y=(train_set_y-m)/v   # centralize, strandarize the data
train_set_y_work=train_set_y_m_work/np.max(train_set_y_m_work)
print(np.shape(train_set_y_work)) 

(256, 120)


In [54]:
def sigmoid(z):
    s=1/(1+np.exp(-z))
    return s

In [55]:
r=8
#initialisation des vecteurs w et b pour la regression , w est un vecteur de taille (64,1)
def initialize_with_zeros(dim):
    w=np.zeros((dim,256),dtype=float)
    b= np.zeros((256,1),dtype=float)
    return w, b
w,b=initialize_with_zeros(64*r)
print(w,b)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]] [[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.

In [56]:
#les étapes de propagation "forward" et "backward" pour l'apprentissage des paramètres.
def propagate(w, b, X, Y):
    r=8
    m = 64*r
    A=sigmoid(np.dot(w.T,X)+b)
    #la fonction coût et son gradient pour la propagation 
    #negative log-likelihood cost for logistic regression
    cost=-(1/m)*(np.sum(Y*np.log(A)+(1-Y)*np.log(1-A)))
    #gradient of the loss par rapport w
    dw=(1/m)*np.dot(X,(A-Y).T)
    #gradient of the loss par rapport b
    db=(1/m)*np.sum(A-Y)
    
    cost = np.squeeze(np.array(cost))
    grads = {"dw": dw,
             "db": db}
    
    return grads, cost

grads, cost=propagate(w, b, train_set_x_orig_all, train_set_y_all)
print(cost)

41.588830833596724


In [57]:
#Cette fonction optimise w et b en exécutant l'algorithme gradient descente
def optimize(w, b, X, Y, num_iterations=100, learning_rate=0.009, print_cost=False):
    w = copy.deepcopy(w)
    b = copy.deepcopy(b)
    
    costs = []
    L=[]
    
    for i in range(num_iterations):
        
        grads, cost = propagate(w, b, X, Y)
        

        # Retrieve derivatives from grads
        dw = grads["dw"]
        db = grads["db"]

        w = w -learning_rate*dw
        b = b -learning_rate*db

        if i % 100 == 0:
            costs.append(cost)
            # Print the cost every 100 training iterations
            if print_cost:
                print ("Cost after iteration %i: %f" %(i, cost))
    
    params = {"w": w,
              "b": b}
    
    grads = {"dw": dw,
             "db": db}
    
    return params, grads, costs 

# params -- dictionnaire contenant les vecteurs w et  b
# grads -- dictionnaire contenant les gradients de la fonction de coût par rapport à w et b
# costs -- liste de tous les coûts calculés pendant l'optimisation,

params, grads, costs =optimize(w, b, train_set_x_orig_all, train_set_y_all, num_iterations=2000, learning_rate=0.009, print_cost=False)
print(params)


{'w': array([[-0.02519511, -0.02513885, -0.02486295, ..., -0.01901138,
        -0.02162788, -0.02024437],
       [-0.02226889, -0.02235254, -0.02195046, ..., -0.0083663 ,
        -0.01459752, -0.01165323],
       [-0.00316279, -0.0033877 , -0.00343997, ...,  0.01214054,
         0.00478256,  0.00806225],
       ...,
       [ 0.00328018,  0.00327284,  0.003237  , ...,  0.00247585,
         0.00281621,  0.0026363 ],
       [ 0.00328018,  0.00327284,  0.003237  , ...,  0.00247585,
         0.00281621,  0.0026363 ],
       [ 0.00328018,  0.00327284,  0.003237  , ...,  0.00247585,
         0.00281621,  0.0026363 ]]), 'b': array([[-1.10058151],
       [-1.10058151],
       [-1.10058151],
       [-1.10058151],
       [-1.10058151],
       [-1.10058151],
       [-1.10058151],
       [-1.10058151],
       [-1.10058151],
       [-1.10058151],
       [-1.10058151],
       [-1.10058151],
       [-1.10058151],
       [-1.10058151],
       [-1.10058151],
       [-1.10058151],
       [-1.10058151],
 

In [58]:
#fonction pour prédire la valeur de contact en utilsant les vecteurs w et b entrainées
def predict(w, b, X):

    A=sigmoid(np.dot(w.T,X)+b)

    return A

predict(params['w'],params['b'],train_set_x_orig_all)

array([[0.00784668, 0.00776747, 0.00871559, ..., 0.00883995, 0.00841069,
        0.00876429],
       [0.00781603, 0.00773545, 0.00873103, ..., 0.00885845, 0.00841333,
        0.00878069],
       [0.00824498, 0.00816328, 0.00918004, ..., 0.0093099 , 0.00885463,
        0.00923039],
       ...,
       [0.03333681, 0.03311437, 0.0269079 , ..., 0.02680322, 0.02846688,
        0.02695722],
       [0.01764206, 0.01750235, 0.01657402, ..., 0.0166492 , 0.01678726,
        0.01663194],
       [0.02412274, 0.02395541, 0.02118673, ..., 0.02120111, 0.02187325,
        0.02124268]])

In [59]:
#construction du model en appllant les fonctions implémentées précedement
def model(X_train, Y_train, X_test, num_iterations=2000, learning_rate=0.5, print_cost=False):
    r=8
    dim = 64*r
    w,b=initialize_with_zeros(dim) 

    params, grads, cost = optimize(w, b, X_train, Y_train, num_iterations, learning_rate, print_cost)
    w = params["w"]
    b = params["b"]
    
    Y_prediction_test = predict(w, b, X_test)
    Y_prediction_train = predict(w, b, X_train)

    # Print train/test Errors
    if print_cost:
        print("train accuracy: {} %".format(100 - np.mean(np.abs(Y_prediction_train - Y_train)) * 100))
        #print("test accuracy: {} %".format(100 - np.mean(np.abs(Y_prediction_test - Y_test)) * 100))
    d = {"costs": cost,
         "Y_prediction_test": Y_prediction_test, 
         "Y_prediction_train" : Y_prediction_train, 
         "w" : w, 
         "b" : b,
         "learning_rate" : learning_rate,
         "num_iterations": num_iterations}
    return d


In [60]:
logistic_regression_model_all = model(train_set_x_orig_all, train_set_y_all, test_set_x_orig_all, num_iterations=10000, learning_rate=0.01, print_cost=True)
print(logistic_regression_model_all)

Cost after iteration 0: 41.588831
Cost after iteration 100: 10.360941
Cost after iteration 200: 10.354911
Cost after iteration 300: 10.352281
Cost after iteration 400: 10.350088
Cost after iteration 500: 10.348135
Cost after iteration 600: 10.346373
Cost after iteration 700: 10.344772
Cost after iteration 800: 10.343308
Cost after iteration 900: 10.341965
Cost after iteration 1000: 10.340728
Cost after iteration 1100: 10.339586
Cost after iteration 1200: 10.338527
Cost after iteration 1300: 10.337545
Cost after iteration 1400: 10.336631
Cost after iteration 1500: 10.335779
Cost after iteration 1600: 10.334983
Cost after iteration 1700: 10.334239
Cost after iteration 1800: 10.333543
Cost after iteration 1900: 10.332889
Cost after iteration 2000: 10.332275
Cost after iteration 2100: 10.331697
Cost after iteration 2200: 10.331153
Cost after iteration 2300: 10.330640
Cost after iteration 2400: 10.330155
Cost after iteration 2500: 10.329697
Cost after iteration 2600: 10.329263
Cost after it

In [61]:
logistic_regression_model_home = model(train_set_x_orig_home, train_set_y_home, test_set_x_orig_home, num_iterations=10000, learning_rate=0.01, print_cost=True)
print(logistic_regression_model_home)

Cost after iteration 0: 41.588831
Cost after iteration 100: 23.698907
Cost after iteration 200: 23.676752
Cost after iteration 300: 23.662612
Cost after iteration 400: 23.652623
Cost after iteration 500: 23.644902
Cost after iteration 600: 23.638501
Cost after iteration 700: 23.632922
Cost after iteration 800: 23.627890
Cost after iteration 900: 23.623251
Cost after iteration 1000: 23.618910
Cost after iteration 1100: 23.614809
Cost after iteration 1200: 23.610909
Cost after iteration 1300: 23.607184
Cost after iteration 1400: 23.603615
Cost after iteration 1500: 23.600185
Cost after iteration 1600: 23.596885
Cost after iteration 1700: 23.593703
Cost after iteration 1800: 23.590631
Cost after iteration 1900: 23.587663
Cost after iteration 2000: 23.584793
Cost after iteration 2100: 23.582013
Cost after iteration 2200: 23.579319
Cost after iteration 2300: 23.576707
Cost after iteration 2400: 23.574172
Cost after iteration 2500: 23.571709
Cost after iteration 2600: 23.569315
Cost after it

In [62]:
logistic_regression_model_others = model(train_set_x_orig_others, train_set_y_others, test_set_x_orig_others, num_iterations=10000, learning_rate=0.01, print_cost=True)
print(logistic_regression_model_others)

Cost after iteration 0: 41.588831
Cost after iteration 100: 10.390756
Cost after iteration 200: 10.355362
Cost after iteration 300: 10.341120
Cost after iteration 400: 10.332731
Cost after iteration 500: 10.327055
Cost after iteration 600: 10.322898
Cost after iteration 700: 10.319686
Cost after iteration 800: 10.317107
Cost after iteration 900: 10.314973
Cost after iteration 1000: 10.313168
Cost after iteration 1100: 10.311613
Cost after iteration 1200: 10.310255
Cost after iteration 1300: 10.309053
Cost after iteration 1400: 10.307980
Cost after iteration 1500: 10.307014
Cost after iteration 1600: 10.306137
Cost after iteration 1700: 10.305336
Cost after iteration 1800: 10.304601
Cost after iteration 1900: 10.303922
Cost after iteration 2000: 10.303293
Cost after iteration 2100: 10.302708
Cost after iteration 2200: 10.302160
Cost after iteration 2300: 10.301648
Cost after iteration 2400: 10.301165
Cost after iteration 2500: 10.300711
Cost after iteration 2600: 10.300281
Cost after it

In [63]:
logistic_regression_model_school = model(train_set_x_orig_school, train_set_y_school, test_set_x_orig_school, num_iterations=10000, learning_rate=0.01, print_cost=True)
print(logistic_regression_model_school)

Cost after iteration 0: 41.588831
Cost after iteration 100: 1.579854
Cost after iteration 200: 1.443315
Cost after iteration 300: 1.398774
Cost after iteration 400: 1.376861
Cost after iteration 500: 1.363914
Cost after iteration 600: 1.355407
Cost after iteration 700: 1.349410
Cost after iteration 800: 1.344968
Cost after iteration 900: 1.341552
Cost after iteration 1000: 1.338849
Cost after iteration 1100: 1.336660
Cost after iteration 1200: 1.334853
Cost after iteration 1300: 1.333339
Cost after iteration 1400: 1.332053
Cost after iteration 1500: 1.330947
Cost after iteration 1600: 1.329988
Cost after iteration 1700: 1.329149
Cost after iteration 1800: 1.328409
Cost after iteration 1900: 1.327752
Cost after iteration 2000: 1.327165
Cost after iteration 2100: 1.326638
Cost after iteration 2200: 1.326162
Cost after iteration 2300: 1.325730
Cost after iteration 2400: 1.325337
Cost after iteration 2500: 1.324978
Cost after iteration 2600: 1.324649
Cost after iteration 2700: 1.324346
Cos

In [64]:
logistic_regression_model_work = model(train_set_x_orig_work, train_set_y_work, test_set_x_orig_work, num_iterations=10000, learning_rate=0.01, print_cost=True)
print(logistic_regression_model_work)

Cost after iteration 0: 41.588831
Cost after iteration 100: 9.374601
Cost after iteration 200: 9.285743
Cost after iteration 300: 9.255487
Cost after iteration 400: 9.239976
Cost after iteration 500: 9.230358
Cost after iteration 600: 9.223682
Cost after iteration 700: 9.218697
Cost after iteration 800: 9.214779
Cost after iteration 900: 9.211585
Cost after iteration 1000: 9.208907
Cost after iteration 1100: 9.206613
Cost after iteration 1200: 9.204611
Cost after iteration 1300: 9.202839
Cost after iteration 1400: 9.201251
Cost after iteration 1500: 9.199812
Cost after iteration 1600: 9.198498
Cost after iteration 1700: 9.197288
Cost after iteration 1800: 9.196165
Cost after iteration 1900: 9.195118
Cost after iteration 2000: 9.194136
Cost after iteration 2100: 9.193211
Cost after iteration 2200: 9.192336
Cost after iteration 2300: 9.191505
Cost after iteration 2400: 9.190714
Cost after iteration 2500: 9.189959
Cost after iteration 2600: 9.189236
Cost after iteration 2700: 9.188542
Cos

In [65]:
data=pd.read_csv(r"E:\Hraf\S8\Projet à Enjeux\Projet Enjeux\source_data\synthetic_contacts_2021.csv")
data=data.to_numpy()

In [71]:
Yr=logistic_regression_model_all["Y_prediction_train"]
Yt=logistic_regression_model_all["Y_prediction_test"]
m=np.max(train_set_y_m_all)
Yr=Yr*m
Yt=Yt*m


C=np.zeros((16,16))
with pd.ExcelWriter(r'E:\Hraf\S8\Projet à Enjeux\Projet Enjeux\matrices de contact predeted\contact_predeted_train_all.xlsx') as writer:
    for i in range(120):
        for j in range(16):
            for k in range(16):
                C[j][k]=Yr[k+16*j][i]
                pd.DataFrame(C).to_excel(writer, sheet_name=f'matrice_{data[((256-(16*(1+10)))+10)+256*(5*i)][0]}', index=False) 

N=np.zeros((16,16))
with pd.ExcelWriter(r'E:\Hraf\S8\Projet à Enjeux\Projet Enjeux\matrices de contact predeted\contact_predeted_test_all.xlsx') as writer:
    for i in range(30):
        for j in range(16):
            for k in range(16):
                N[j][k]=Yr[k+16*j][i]
                pd.DataFrame(N).to_excel(writer, sheet_name=f'matrice_{data[((256-(16*(1+10)))+10)+256*(5*(i+120))][0]}', index=False) 

    


In [72]:
Yr=logistic_regression_model_home["Y_prediction_train"]
Yt=logistic_regression_model_home["Y_prediction_test"]
m=np.max(train_set_y_m_home)
Yr=Yr*m
Yt=Yt*m


C=np.zeros((16,16))
with pd.ExcelWriter(r'E:\Hraf\S8\Projet à Enjeux\Projet Enjeux\matrices de contact predeted\contact_predeted_train_home.xlsx') as writer:
    for i in range(120):
        for j in range(16):
            for k in range(16):
                C[j][k]=Yr[k+16*j][i]
                pd.DataFrame(C).to_excel(writer, sheet_name=f'matrice_{data[((256-(16*(1+10)))+10)+256*(5*i)][0]}', index=False) 

N=np.zeros((16,16))
with pd.ExcelWriter(r'E:\Hraf\S8\Projet à Enjeux\Projet Enjeux\matrices de contact predeted\contact_predeted_test_home.xlsx') as writer:
    for i in range(30):
        for j in range(16):
            for k in range(16):
                N[j][k]=Yr[k+16*j][i]
                pd.DataFrame(N).to_excel(writer, sheet_name=f'matrice_{data[((256-(16*(1+10)))+10)+256*(5*(i+120))][0]}', index=False) 

In [73]:
Yr=logistic_regression_model_others["Y_prediction_train"]
Yt=logistic_regression_model_others["Y_prediction_test"]
m=np.max(train_set_y_m_others)
Yr=Yr*m
Yt=Yt*m


C=np.zeros((16,16))
with pd.ExcelWriter(r'E:\Hraf\S8\Projet à Enjeux\Projet Enjeux\matrices de contact predeted\contact_predeted_train_others.xlsx') as writer:
    for i in range(120):
        for j in range(16):
            for k in range(16):
                C[j][k]=Yr[k+16*j][i]
                pd.DataFrame(C).to_excel(writer, sheet_name=f'matrice_{data[((256-(16*(1+10)))+10)+256*(5*i)][0]}', index=False) 

N=np.zeros((16,16))
with pd.ExcelWriter(r'E:\Hraf\S8\Projet à Enjeux\Projet Enjeux\matrices de contact predeted\contact_predeted_test_others.xlsx') as writer:
    for i in range(30):
        for j in range(16):
            for k in range(16):
                N[j][k]=Yr[k+16*j][i]
                pd.DataFrame(N).to_excel(writer, sheet_name=f'matrice_{data[((256-(16*(1+10)))+10)+256*(5*(i+120))][0]}', index=False) 

In [69]:
Yr=logistic_regression_model_school["Y_prediction_train"]
Yt=logistic_regression_model_school["Y_prediction_test"]
m=np.max(train_set_y_m_school)
Yr=Yr*m
Yt=Yt*m


C=np.zeros((16,16))
with pd.ExcelWriter(r'E:\Hraf\S8\Projet à Enjeux\Projet Enjeux\matrices de contact predeted\contact_predeted_train_school.xlsx') as writer:
    for i in range(120):
        for j in range(16):
            for k in range(16):
                C[j][k]=Yr[k+16*j][i]
                pd.DataFrame(C).to_excel(writer, sheet_name=f'matrice_{data[((256-(16*(1+10)))+10)+256*(5*i)][0]}', index=False) 

N=np.zeros((16,16))
with pd.ExcelWriter(r'E:\Hraf\S8\Projet à Enjeux\Projet Enjeux\matrices de contact predeted\contact_predeted_test_school.xlsx') as writer:
    for i in range(30):
        for j in range(16):
            for k in range(16):
                N[j][k]=Yr[k+16*j][i]
                pd.DataFrame(N).to_excel(writer, sheet_name=f'matrice_{data[((256-(16*(1+10)))+10)+256*(5*(i+120))][0]}', index=False) 

In [70]:
Yr=logistic_regression_model_work["Y_prediction_train"]
Yt=logistic_regression_model_work["Y_prediction_test"]
m=np.max(train_set_y_m_work)
Yr=Yr*m
Yt=Yt*m


C=np.zeros((16,16))
with pd.ExcelWriter(r'E:\Hraf\S8\Projet à Enjeux\Projet Enjeux\matrices de contact predeted\contact_predeted_train_work.xlsx') as writer:
    for i in range(120):
        for j in range(16):
            for k in range(16):
                C[j][k]=Yr[k+16*j][i]
                pd.DataFrame(C).to_excel(writer, sheet_name=f'matrice_{data[((256-(16*(1+10)))+10)+256*(5*i)][0]}', index=False) 

N=np.zeros((16,16))
with pd.ExcelWriter(r'E:\Hraf\S8\Projet à Enjeux\Projet Enjeux\matrices de contact predeted\contact_predeted_test_work.xlsx') as writer:
    for i in range(30):
        for j in range(16):
            for k in range(16):
                N[j][k]=Yr[k+16*j][i]
                pd.DataFrame(N).to_excel(writer, sheet_name=f'matrice_{data[((256-(16*(1+10)))+10)+256*(5*(i+120))][0]}', index=False) 